### ISSUE TITLE
Saving JT-File.

### ISSUE THREAD

**Issue by christian-demel-horsch** [space928/JTConvert#3]
HI Thomas, 

thanks for sharing this project. Currently I got some trouble with the RGB Code applied to my JT-Files. Therefor I would like to modify the JT File directly. I was looking for some code like yours. It works for JT Versions <10.0 to read the material information, but I would like to modify an save the new JT. I was hoping you could help me with it. Do you have a way yet to modify and save the jt-FIles?  This would be awesome and a huge shortcut for me. 

Take care and thank you 👍

**Comment by space928** [comment]
Hi,
As this is a hobby project, I can't devote much time to it unfortunately. As it stands I haven't implemented anything to write or modify JT files. Since the material attribute element is only compressed with LZMA, it's probably not too difficult to modify the file without having to fully parse and rewrite it. My code can already parse the logical scene graph segment which stores the material attribute elements so what you would need to do is modify the parsed Logical Scene Graph segment, rewrite and recompress it and then append it to the end of the JT file and update the table of contents with it's new location and size.
